<?php

/**
 * This enum was autogenerated
 * Do NOT edit
 */

declare(strict_types=1);

namespace Pedros80\TfLphp\Enums;

enum DLRSeverityCodes: int
{
    case SPECIAL_SERVICE     = 0;
    case CLOSED              = 1;
    case SUSPENDED           = 2;
    case PART_SUSPENDED      = 3;
    case PLANNED_CLOSURE     = 4;
    case PART_CLOSURE        = 5;
    case SEVERE_DELAYS       = 6;
    case REDUCED_SERVICE     = 7;
    case BUS_SERVICE         = 8;
    case MINOR_DELAYS        = 9;
    case GOOD_SERVICE        = 10;
    case PART_CLOSED         = 11;
    case EXIT_ONLY           = 12;
    case NO_STEP_FREE_ACCESS = 13;
    case CHANGEOFFREQUENCY   = 14;
    case DIVERTED            = 15;
    case NOT_RUNNING         = 16;
    case ISSUES_REPORTED     = 17;
    case NO_ISSUES           = 18;
    case INFORMATION         = 19;
    case SERVICE_CLOSED      = 20;
}
