<?php

/**
 * This enum was autogenerated
 * Do NOT edit
 */

declare(strict_types=1);

namespace Pedros80\TfLphp\Enums;

enum JourneyPlannerModes: string
{
    case BLACK_CAB_AS_CUSTOMER     = 'black-cab-as-customer';
    case BLACK_CAB_AS_DRIVER       = 'black-cab-as-driver';
    case BUS                       = 'bus';
    case CABLE_CAR                 = 'cable-car';
    case COACH                     = 'coach';
    case CYCLE                     = 'cycle';
    case CYCLE_HIRE                = 'cycle-hire';
    case DLR                       = 'dlr';
    case ELECTRIC_CAR              = 'electric-car';
    case ELIZABETH_LINE            = 'elizabeth-line';
    case GOODS_VEHICLE_AS_DRIVER   = 'goods-vehicle-as-driver';
    case INTERCHANGE_KEEP_SITTING  = 'interchange-keep-sitting';
    case INTERCHANGE_SECURE        = 'interchange-secure';
    case INTERNATIONAL_RAIL        = 'international-rail';
    case MOTORBIKE_SCOOTER         = 'motorbike-scooter';
    case NATIONAL_RAIL             = 'national-rail';
    case OVERGROUND                = 'overground';
    case PLANE                     = 'plane';
    case PRIVATE_CAR               = 'private-car';
    case PRIVATE_COACH_AS_CUSTOMER = 'private-coach-as-customer';
    case PRIVATE_COACH_AS_DRIVER   = 'private-coach-as-driver';
    case PRIVATE_HIRE_AS_CUSTOMER  = 'private-hire-as-customer';
    case PRIVATE_HIRE_AS_DRIVER    = 'private-hire-as-driver';
    case REPLACEMENT_BUS           = 'replacement-bus';
    case RIVER_BUS                 = 'river-bus';
    case RIVER_TOUR                = 'river-tour';
    case TAXI                      = 'taxi';
    case TRAM                      = 'tram';
    case TUBE                      = 'tube';
    case WALKING                   = 'walking';
}
