<?php

/**
 * This enum was autogenerated
 * Do NOT edit
 */

declare(strict_types=1);

namespace Pedros80\TfLphp\Enums;

enum LineServiceTypes: string
{
    case REGULAR = 'Regular';
    case NIGHT   = 'Night';
}
