<?php

/**
 * This enum was autogenerated
 * Do NOT edit
 */

declare(strict_types=1);

namespace Pedros80\TfLphp\Enums;

enum PlaceTypes: string
{
    case AREA_FOR_INTENSIFICATION        = 'AreaForIntensification';
    case BIKE_POINT                      = 'BikePoint';
    case BOROUGHS                        = 'Boroughs';
    case CABWISE                         = 'Cabwise';
    case CAR_PARK                        = 'CarPark';
    case CENSUS_OUTPUT_AREAS             = 'CensusOutputAreas';
    case CENSUS_SUPER_OUTPUT_AREAS       = 'CensusSuperOutputAreas';
    case CENTRAL_ACTIVITY_ZONE           = 'CentralActivityZone';
    case CHARGE_CONNECTOR                = 'ChargeConnector';
    case CHARGE_STATION                  = 'ChargeStation';
    case COACH_BAY                       = 'CoachBay';
    case COACH_PARK                      = 'CoachPark';
    case CYCLE_PARK                      = 'CyclePark';
    case JAM_CAM                         = 'JamCam';
    case ON_STREET_METERED_BAY           = 'OnStreetMeteredBay';
    case OPPORTUNITY_AREAS               = 'OpportunityAreas';
    case OTHER_COACH_PARKING             = 'OtherCoachParking';
    case OYSTER_TICKET_SHOP              = 'OysterTicketShop';
    case RED_LIGHT_AND_SPEED_CAM         = 'RedLightAndSpeedCam';
    case RED_LIGHT_CAM                   = 'RedLightCam';
    case SPEED_CAM                       = 'SpeedCam';
    case TAXI_RANK                       = 'TaxiRank';
    case VARIABLE_MESSAGE_SIGN           = 'VariableMessageSign';
    case WARDS                           = 'Wards';
    case WATERFREIGHT_BRIDGE             = 'WaterfreightBridge';
    case WATERFREIGHT_DOCK               = 'WaterfreightDock';
    case WATERFREIGHT_JETTY              = 'WaterfreightJetty';
    case WATERFREIGHT_LOCK               = 'WaterfreightLock';
    case WATERFREIGHT_OTHER_ACCESS_POINT = 'WaterfreightOther Access Point';
    case WATERFREIGHT_TUNNEL             = 'WaterfreightTunnel';
    case WATERFREIGHT_WHARF              = 'WaterfreightWharf';
}
