<?php

/**
 * This enum was autogenerated
 * Do NOT edit
 */

declare(strict_types=1);

namespace Pedros80\TfLphp\Enums;

enum RailLines: string
{
    case LONDON_CABLE_CAR  = 'london-cable-car';
    case DLR               = 'dlr';
    case THAMESLINK        = 'thameslink';
    case NATIONAL_RAIL     = 'national-rail';
    case LONDON_OVERGROUND = 'london-overground';
    case ELIZABETH         = 'elizabeth';
    case TRAM              = 'tram';
    case BAKERLOO          = 'bakerloo';
    case CENTRAL           = 'central';
    case CIRCLE            = 'circle';
    case DISTRICT          = 'district';
    case HAMMERSMITH_CITY  = 'hammersmith-city';
    case JUBILEE           = 'jubilee';
    case METROPOLITAN      = 'metropolitan';
    case NORTHERN          = 'northern';
    case PICCADILLY        = 'piccadilly';
    case VICTORIA          = 'victoria';
    case WATERLOO_CITY     = 'waterloo-city';

    public function toMode(): string
    {
        return match ($this) {
            self::LONDON_CABLE_CAR  => 'cableCar',
            self::DLR               => 'dlr',
            self::THAMESLINK        => 'nationalRail',
            self::NATIONAL_RAIL     => 'nationalRail',
            self::LONDON_OVERGROUND => 'overground',
            self::ELIZABETH         => 'elizabeth-line',
            self::TRAM              => 'tram',
            self::BAKERLOO          => 'tube',
            self::CENTRAL           => 'tube',
            self::CIRCLE            => 'tube',
            self::DISTRICT          => 'tube',
            self::HAMMERSMITH_CITY  => 'tube',
            self::JUBILEE           => 'tube',
            self::METROPOLITAN      => 'tube',
            self::NORTHERN          => 'tube',
            self::PICCADILLY        => 'tube',
            self::VICTORIA          => 'tube',
            self::WATERLOO_CITY     => 'tube',
        };
    }
}
