<?php

/**
 * This enum was autogenerated
 * Do NOT edit
 */

declare(strict_types=1);

namespace Pedros80\TfLphp\Enums;

enum RoadIds: string
{
    case A1                    = 'a1';
    case A10                   = 'a10';
    case A12                   = 'a12';
    case A13                   = 'a13';
    case A2                    = 'a2';
    case A20                   = 'a20';
    case A205                  = 'a205';
    case A21                   = 'a21';
    case A23                   = 'a23';
    case A24                   = 'a24';
    case A3                    = 'a3';
    case A316                  = 'a316';
    case A4                    = 'a4';
    case A40                   = 'a40';
    case A406                  = 'a406';
    case A41                   = 'a41';
    case BISHOPSGATECROSSROUTE = 'bishopsgate cross route';
    case BLACKWALLTUNNEL       = 'blackwall tunnel';
    case CITYROUTE             = 'city route';
    case FARRINGDONCROSSROUTE  = 'farringdon cross route';
    case INNERRING             = 'inner ring';
    case SOUTHERNRIVERROUTE    = 'southern river route';
    case WESTERNCROSSROUTE     = 'western cross route';
}
