<?php

/**
 * This enum was autogenerated
 * Do NOT edit
 */

declare(strict_types=1);

namespace Pedros80\TfLphp\Enums;

enum StopPointInformationCategories: string
{
    case ACCESSIBILITY        = 'Accessibility';
    case ADDRESS              = 'Address';
    case DIRECTION            = 'Direction';
    case FACILITY             = 'Facility';
    case GEO                  = 'Geo';
    case NEAREST_PLACES       = 'NearestPlaces';
    case OPENING_TIME         = 'Opening Time';
    case SERVICE_INFO         = 'ServiceInfo';
    case STATION_OWNED_BY_TFL = 'StationOwnedByTfl';
    case VISITOR_CENTRE       = 'VisitorCentre';

    public function availableKeys(): array
    {
        return match ($this) {
            self::ACCESSIBILITY        => ['TaxiRankOutsideStation', 'SpecificEntranceRequired', 'AddtionalInformation', 'LimitedCapacityLift', 'ToiletNote', 'SpecificEntranceInstructions', 'Toilet', 'AccessViaLift', 'BlueBadgeCarParkSpaces'],
            self::ADDRESS              => ['PhoneNo', 'Address'],
            self::DIRECTION            => ['Towards', 'CompassPoint'],
            self::FACILITY             => ['Boarding Ramp', 'Lifts', 'Cash Machines', 'Waiting Room', 'Euro Cash Machines', 'Payphones', 'ASDA Click and Collect', 'Ticket Halls', 'Boarding Ramps', 'Escalators', 'Help Points', 'WiFi', 'Bridge', 'Car park', 'Left Luggage', 'Photo Booths', 'Amazon Lockers', 'Other Facilities', 'Gates', 'Toilets'],
            self::GEO                  => ['Zone'],
            self::NEAREST_PLACES       => ['SourceSystemPlaceId'],
            self::OPENING_TIME         => ['SunFrom', 'MonFriFrom', 'MonFriTo', 'SatTo', 'SunTo', 'SatFrom'],
            self::SERVICE_INFO         => ['Night'],
            self::STATION_OWNED_BY_TFL => ['OwnedByTfl'],
            self::VISITOR_CENTRE       => ['Location'],
        };
    }
}
