<?php

/**
 * This enum was autogenerated
 * Do NOT edit
 */

declare(strict_types=1);

namespace Pedros80\TfLphp\Enums;

enum StopPointTypes: string
{
    case CAR_PICKUP_SET_DOWN_AREA               = 'CarPickupSetDownArea';
    case NAPTAN_AIR_ACCESS_AREA                 = 'NaptanAirAccessArea';
    case NAPTAN_AIR_ENTRANCE                    = 'NaptanAirEntrance';
    case NAPTAN_AIRPORT_BUILDING                = 'NaptanAirportBuilding';
    case NAPTAN_BUS_COACH_STATION               = 'NaptanBusCoachStation';
    case NAPTAN_BUS_WAY_POINT                   = 'NaptanBusWayPoint';
    case NAPTAN_COACH_ACCESS_AREA               = 'NaptanCoachAccessArea';
    case NAPTAN_COACH_BAY                       = 'NaptanCoachBay';
    case NAPTAN_COACH_ENTRANCE                  = 'NaptanCoachEntrance';
    case NAPTAN_COACH_SERVICE_COVERAGE          = 'NaptanCoachServiceCoverage';
    case NAPTAN_COACH_VARIABLE_BAY              = 'NaptanCoachVariableBay';
    case NAPTAN_FERRY_ACCESS_AREA               = 'NaptanFerryAccessArea';
    case NAPTAN_FERRY_BERTH                     = 'NaptanFerryBerth';
    case NAPTAN_FERRY_ENTRANCE                  = 'NaptanFerryEntrance';
    case NAPTAN_FERRY_PORT                      = 'NaptanFerryPort';
    case NAPTAN_FLEXIBLE_ZONE                   = 'NaptanFlexibleZone';
    case NAPTAN_HAIL_AND_RIDE_SECTION           = 'NaptanHailAndRideSection';
    case NAPTAN_LIFT_CABLE_CAR_ACCESS_AREA      = 'NaptanLiftCableCarAccessArea';
    case NAPTAN_LIFT_CABLE_CAR_ENTRANCE         = 'NaptanLiftCableCarEntrance';
    case NAPTAN_LIFT_CABLE_CAR_STOP             = 'NaptanLiftCableCarStop';
    case NAPTAN_LIFT_CABLE_CAR_STOP_AREA        = 'NaptanLiftCableCarStopArea';
    case NAPTAN_MARKED_POINT                    = 'NaptanMarkedPoint';
    case NAPTAN_METRO_ACCESS_AREA               = 'NaptanMetroAccessArea';
    case NAPTAN_METRO_ENTRANCE                  = 'NaptanMetroEntrance';
    case NAPTAN_METRO_PLATFORM                  = 'NaptanMetroPlatform';
    case NAPTAN_METRO_STATION                   = 'NaptanMetroStation';
    case NAPTAN_ONSTREET_BUS_COACH_STOP_CLUSTER = 'NaptanOnstreetBusCoachStopCluster';
    case NAPTAN_ONSTREET_BUS_COACH_STOP_PAIR    = 'NaptanOnstreetBusCoachStopPair';
    case NAPTAN_PRIVATE_BUS_COACH_TRAM          = 'NaptanPrivateBusCoachTram';
    case NAPTAN_PUBLIC_BUS_COACH_TRAM           = 'NaptanPublicBusCoachTram';
    case NAPTAN_RAIL_ACCESS_AREA                = 'NaptanRailAccessArea';
    case NAPTAN_RAIL_ENTRANCE                   = 'NaptanRailEntrance';
    case NAPTAN_RAIL_PLATFORM                   = 'NaptanRailPlatform';
    case NAPTAN_RAIL_STATION                    = 'NaptanRailStation';
    case NAPTAN_SHARED_TAXI                     = 'NaptanSharedTaxi';
    case NAPTAN_TAXI_RANK                       = 'NaptanTaxiRank';
    case NAPTAN_UNMARKED_POINT                  = 'NaptanUnmarkedPoint';
    case TRANSPORT_INTERCHANGE                  = 'TransportInterchange';
}
