<?php

/**
 * This enum was autogenerated
 * Do NOT edit
 */

declare(strict_types=1);

namespace Pedros80\TfLphp\Enums;

enum StopPointModes: string
{
    case BUS                      = 'bus';
    case CABLE_CAR                = 'cable-car';
    case COACH                    = 'coach';
    case CYCLE                    = 'cycle';
    case CYCLE_HIRE               = 'cycle-hire';
    case DLR                      = 'dlr';
    case ELIZABETH_LINE           = 'elizabeth-line';
    case INTERCHANGE_KEEP_SITTING = 'interchange-keep-sitting';
    case INTERCHANGE_SECURE       = 'interchange-secure';
    case NATIONAL_RAIL            = 'national-rail';
    case OVERGROUND               = 'overground';
    case REPLACEMENT_BUS          = 'replacement-bus';
    case RIVER_BUS                = 'river-bus';
    case RIVER_TOUR               = 'river-tour';
    case TAXI                     = 'taxi';
    case TRAM                     = 'tram';
    case TUBE                     = 'tube';
    case WALKING                  = 'walking';
}
